eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: client
  rabbitmq:
    host: localhost:15672
    username: guest
    password: guest
env: 
  dev
