eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev      
spring:
  application:
    name: client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
cc：
  cccc
